Redirection of here doc to man fails on OSX, use tmp file instead.

diff --git a/getip b/getip
--- a/getip
+++ b/getip
@@ -382,11 +382,25 @@ GetIpMultipleValidIP="2"
 GetIpTimedOut="3"
 
 
-# Display help by redirecting the text of the man page to 'man'.
+# Display help by redirecting the text of the man page to a temp file and displaying it using man.
 Display_Usage_Message()
 {
+    # Create a temp file to store the man page here document.
+    # -q to fail silently on error and -t to use the system's temp directory.
+    # Don't use 'local' for 'tempFileNameForGetIpManPage' or $? won't work.
+    tempFileNameForGetIpManPage=$(mktemp -q -t "getip.man.tmp.XXXXXX")
+    local mktempFileCreationRetVal=$?
 
-man /dev/stdin <<EOF
+    echo "mktempFileCreationRetVal: $mktempFileCreationRetVal"
+
+    if [ "$mktempFileCreationRetVal" -ne "0" ]; then
+        Output_Error_Message "TempFileCreationFailed"
+        exit "$ExitStatusErrorTempFileCreationFailed"
+    fi
+
+# Output a here document of the getip man page to $tempFileNameForGetIpManPage.
+# Here documents won't work well with indentation, keep to the hard left.
+cat >>$tempFileNameForGetIpManPage <<EOF
 
 .TH GETIP 1 "29 Sep 2015" "1.0" "GETIP VERSION 1.0"
 
@@ -477,6 +491,12 @@ Feel free to submit new IP address providing web pages to be added to the source
 .SH AUTHOR
 <mattst@i-dig.info>
 EOF
+
+    # Display the man page.
+    man "$tempFileNameForGetIpManPage"
+
+    # Delete the temp file.
+    if [ -f "$tempFileNameForGetIpManPage" ]; then rm "$tempFileNameForGetIpManPage"; fi
 }
 
 
@@ -1448,6 +1468,7 @@ if [ "$operationMode" = "TESTURL" ]; then
 
     # Create a temp file for Get_Ip_From_Url() to use. The options used are:
     # -q to fail silently on error and -t to use the system's temp directory.
+    # Don't use 'local' for 'tempFileNameForGetIpManPage' or $? won't work.
     tempFileNameForGetIp=$(mktemp -q -t "getip.tmp.XXXXXX")
     mktempFileCreationRetVal=$?
 
@@ -1540,6 +1561,7 @@ for url in "${urlArray[@]}"; do
 
     # Create a temp file for Get_Ip_From_Url() to use. The options used are:
     # -q to fail silently on error and -t to use the system's temp directory.
+    # Don't use 'local' for 'tempFileNameForGetIpManPage' or $? won't work.
     tempFileNameForGetIp=$(mktemp -q -t "getip.tmp.XXXXXX")
     mktempFileCreationRetVal=$?
 
